spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_users
    username: root
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: mysql
    show-sql: true