spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_users
    username: root
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: mysql
    show-sql: true

message:
  exceptions:
    employee:
      not-found: "Employee not found, with id: "
    department:
      not-found: "Department not found, with id: "
  controller:
    employee:
      delete:
        success: "Deleted successfully"
    department:
      delete:
        success: "Deleted successfully"